### ISSUE TITLE
Thermostat only displaying Fahrenheit 

### ISSUE THREAD

**Issue by arakasi55** [excaliburpartners/HAILogger#11] opened 2019-06-12 05:27 UTC
Although OmniPro is configured and reporting temperature settings in Celsius, OmniLinkBridge appears to be defaulting the MQTT topic omnilink/thermostat1 to Fahrenheit. Configuration.yaml has been set for metric and celsius units

The zone 16 thermostat temp sensor is correctly seen as Celsius

<img width="122" alt="Screen Shot 2019-05-12 at 1 01 50 pm" src="https://user-images.githubusercontent.com/51733827/59325184-689df700-8d25-11e9-8075-70833d9d4680.png">

As can be seen, Lovelace is even showing the Celsius scale
<img width="385" alt="Screen Shot 2019-05-12 at 1 01 57 pm" src="https://user-images.githubusercontent.com/51733827/59325185-689df700-8d25-11e9-9452-e733ab93416c.png">

MQTT messages can be seen with the temps in Fahrenheit however
<img width="226" alt="Screen Shot 2019-06-12 at 3 21 12 pm" src="https://user-images.githubusercontent.com/51733827/59325273-bdda0880-8d25-11e9-8394-a2e0abfd631f.png">

**Comment by mattstein111** [comment] 2019-06-12 09:07
I'm seeing various similar issues when integrating to SmartThings, although they only seem to apply to thermostats, not temp sensors. In this case, the Thermostat is Omnistat RC2000, but it looks like the issue is between OmniLinkBridge and the OmniPro, although I'm not sure.

**Comment by arakasi55** [comment] 2019-06-13 09:43
I'm also using an RC2000. The status from the OmniPro is definitely showing the temp settings in celsius, but the MQTT messages are being converted to F

**Comment by mattstein111** [comment] 2019-06-13 09:56
> I'm also using an RC2000. The status from the OmniPro is definitely showing the temp settings in celsius, but the MQTT messages are being converted to F

I'm not so sure. The interface between OmniLinkBridge and SmartThings isn't MQTT (afaik), and SmartThings is getting F data from OLB.

**Comment by rwagoner** [comment] 2019-10-28 01:26
This is due to me assuming everyone uses fahrenheit. I added the capability to read the temperature format from the controller in the dev branch and it will be released in 1.1.4.

**Closed as completed by rwagoner** 2019-10-28 01:26 UTC
