### ISSUE TITLE
Missing "supported_feature" option on Thermostats?

### ISSUE THREAD

**Issue by madasus** [excaliburpartners/HAILogger#52] opened 2022-11-07 12:02 UTC
Hello,

I've been working with another integration (scheduler-card) and finding that the integration isn't able to adjust the temperatures for the OmniLinkBridge thermostats.  The developer noticed a few issues with the implementation of the thermostats.

https://github.com/nielsfaber/scheduler-card/issues/618#issuecomment-1305122296

is this an easy fix?

**Comment by rwagoner** [comment] 2022-11-07 12:53
OmniLinkBridge uses the [MQTT HVAC (Climate)](https://www.home-assistant.io/integrations/climate.mqtt/) integration for thermostats. It provides discovery information over MQTT to allow Home Assistant MQTT to configure the devices. Looking at the docs, MQTT HVAC only supports auto, heat, cool, and off for mode. I tested sending heat_cool and it breaks the thermostat. Are you able to create an issue with MQTT HVAC? Once they make the changes, I can make the changes to OmniLinkBridge.

**Comment by madasus** [comment] 2022-11-07 12:59
done - thank you for responding so fast.

**Comment by nielsfaber** [comment] 2022-11-07 13:15
Maybe it's possible for one of you to post the discovery message payload?
Looking at the [HA implementation](https://github.com/home-assistant/core/blob/934cec9778c220355bc3d407bf062a668aa81c92/homeassistant/components/mqtt/climate.py#L467-L470), the supported_features property is automatically calculated based on the provided discovery information.
HA expects a `temperature_state_topic` and/or `temperature_command_topic ` for a climate device which supports heat mode or cool mode. Is this provided?

**Comment by madasus** [comment] 2022-11-07 13:29
Here is the discovery topic from OmniLinkBridge

{"status":null,"action_topic":"omnilink/thermostat1/current_operation","current_temperature_topic":"omnilink/thermostat1/current_temperature","temperature_low_state_topic":"omnilink/thermostat1/temperature_heat_state","temperature_low_command_topic":"omnilink/thermostat1/temperature_heat_command","temperature_high_state_topic":"omnilink/thermostat1/temperature_cool_state","temperature_high_command_topic":"omnilink/thermostat1/temperature_cool_command","min_temp":"45","max_temp":"95","mode_state_topic":"omnilink/thermostat1/mode_basic_state","mode_command_topic":"omnilink/thermostat1/mode_command","modes":["off","heat"],"fan_mode_state_topic":"omnilink/thermostat1/fan_mode_state","fan_mode_command_topic":"omnilink/thermostat1/fan_mode_command","fan_modes":["auto","on","cycle"],"preset_mode_state_topic":"omnilink/thermostat1/hold_state","preset_mode_command_topic":"omnilink/thermostat1/hold_command","preset_modes":["off","on","vacation"],"unique_id":"omnilinkthermostat1","name":"Sunroom","availability":[{"topic":"omnilink/status"},{"topic":"omnilink/thermostat1/status"}],"availability_mode":"all","device":{"identifiers":"omnilink","name":"omnilink","sw_version":"0.0 - OmniLinkBridge 1.1.14.0","model":"OmniPro II","manufacturer":"Leviton"}}

Here is the one from the waterfurnace thermostats

{"name":"WaterFurnace Zone 1","availability_topic":"homie/aurora-xxxxxxxxx/$state","payload_available":"ready","payload_not_available":"lost","qos":1,"device":{"manufacturer":"WaterFurnace","sw_version":"1.4.6","model":"NVVXXXXXXXX","name":"WaterFurnace","identifiers":"aurora-xxxxxxxxx"},"unique_id":"aurora-xxxxxxxxx_zone1","action_topic":"homie/aurora-xxxxxxxxx/zone1/current-mode","action_template":"{% if value.startswith('h') %}\n  heating\n{% elif value.startswith('c') %}\n  cooling\n{% elif value == 'standby' %}\n  idle\n{% endif %}\n","current_temperature_topic":"homie/aurora-xxxxxxxxx/zone1/ambient-temperature","fan_mode_state_topic":"homie/aurora-xxxxxxxxx/zone1/target-fan-mode","fan_mode_command_topic":"homie/aurora-xxxxxxxxx/zone1/target-fan-mode/set","mode_state_topic":"homie/aurora-xxxxxxxxx/zone1/target-mode","mode_command_topic":"homie/aurora-xxxxxxxxx/zone1/target-mode/set","temperature_high_state_topic":"homie/aurora-xxxxxxxxx/zone1/cooling-target-temperature","temperature_high_command_topic":"homie/aurora-xxxxxxxxx/zone1/cooling-target-temperature/set","temperature_high_command_template":"{{ value | round(0) }}","temperature_low_state_topic":"homie/aurora-xxxxxxxxx/zone1/heating-target-temperature","temperature_low_command_topic":"homie/aurora-xxxxxxxxx/zone1/heating-target-temperature/set","temperature_low_command_template":"{{ value | round(0) }}","min_temp":40,"max_temp":99,"temperature_unit":"F","modes":["off","auto","cool","heat"],"fan_modes":["auto","continuous","intermittent"]}

**Comment by nielsfaber** [comment] 2022-11-07 13:36
So the problem is that:
- temperature_low_state_topic
- temperature_low_command_topic
- temperature_high_state_topic
- temperature_high_command_topic

Are provided, while these are intended for mode `heat_cool` (regulating between a min/max temp range).

While:
- temperature_state_topic 
- temperature_command_topic

Are missing, which are used (i.e. required) for the `heat` and `cool` modes.

So the temperature setpoint topics are not matched with the modes which are advertised to be supported.
This is a problem of this integration, not caused in HA.

**Comment by madasus** [comment] 2022-11-07 13:39
so something that needs to be fixed in OmniLinkBridge or something in the MQTT HVAC module?

**Comment by nielsfaber** [comment] 2022-11-07 14:25
@madasus Here, in OmniLinkBridge.
Specifically: https://github.com/excaliburpartners/OmniLinkBridge/blob/495ce74149606bd1375e028ddd3a5620f165d27d/OmniLinkBridge/MQTT/HomeAssistant/Climate.cs#L12-L16
and:
https://github.com/excaliburpartners/OmniLinkBridge/blob/495ce74149606bd1375e028ddd3a5620f165d27d/OmniLinkBridge/MQTT/MappingExtensions.cs#L526-L530

They should be renamed to `temperature_state_topic` and `temperature_command_topic`, as a result there are no independent setpoints for cooling vs heating modes.
It's up to @rwagoner to determine if this has any negative consequence.

You can close the issue you opened in the HA repo, since there's no issue on their side.

**Comment by ccutrer** [comment] 2022-11-07 15:03
> So the problem is that:
> 
> * temperature_low_state_topic
> * temperature_low_command_topic
> * temperature_high_state_topic
> * temperature_high_command_topic
> 
> Are provided, while these are intended for mode `heat_cool` (regulating between a min/max temp range).
> 
> While:
> 
> * temperature_state_topic
> * temperature_command_topic
> 
> Are missing, which are used (i.e. required) for the `heat` and `cool` modes.
> 
> So the temperature setpoint topics are not matched with the modes which are advertised to be supported. This is a problem of this integration, not caused in HA.

Hi, I'm the developer of https://github.com/ccutrer/waterfurnace_aurora here. I'm not much of a HASS guy, but I do provide HASS discovery topics with my bridge to allow people to use it with HASS. Are there any docs that explain which topics are expected for which modes? For example, looking through https://www.home-assistant.io/integrations/climate.mqtt/ again, there's nothing that says that "auto" mode (or heat_cool??) expects `temperature_high_*_topic` and `temperature_low_*_topic`, while heat and cool modes _only_ use `temperature_*_topic`. A naive developer such as myself would assume HASS is smart enough that when in heat mode, to prefer temperature_low if it exists, otherwise use generic temperature. I need to go revisit another integration, but I'm pretty sure that's how Apple HomeKit works when a thermostat has both heating/cooling set points _and_ a generic set point.

**Comment by nielsfaber** [comment] 2022-11-07 15:42
Hi @ccutrer 
Unfortunately documentation in HA is very limited, but hopefully I can clarify things a bit for you.

In the [MQTT Climate](https://www.home-assistant.io/integrations/climate.mqtt/) page you can read:
> temperature_low_command_topic string (optional)
The MQTT topic to publish commands to change the target low temperature.

> temperature_low_state_topic string (optional)
The MQTT topic to subscribe for changes in the target low temperature. If this is not set, the target low temperature works in optimistic mode (see below).

I.e. these topics correspond to the 'target low temperature'.

In the [service definition](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature) for climate devices you can read:
> target_temp_low | yes | The lowest temperature that the climate device will allow. Required if hvac_mode is heat_cool. Required together with target_temp_high.

I agree that it's not 100% evident from the documentation, but in summary (and in my own experience):
* When a HA climate entity is in `hvac_mode` `heat` or `cool`, you use service `climate.set_temperature` with `temperature: <setpoint value>` as data to control it. Similarly in MQTT you use the `temperature_command_topic`.
* When a HA climate entity is in `hvac_mode` `heat_cool`, you use service `climate.set_temperature` with `target_temp_low: <setpoint value lower bound>` and `target_temp_high: <setpoint value upper bound>` as data to control it. Similarly in MQTT you use the `temperature_low_command_topic` and `temperature_high_command_topic`.

So, in HA,  the `low` and `high` setpoint topics are not for distinguishing between mode cool and heat, but to control a device to regulate within a certain temperature range. 

Moreover, in HA the mode and setpoint are completely separated from eachother. You can send a setpoint of 20C and subsequently switch between cool, heat and even off. The setpoint remains unaffected by changes in the mode, and the mode remains unaffected by changing the setpoint.

> A naive developer such as myself would assume HASS is smart enough that when in heat mode, to prefer temperature_low if it exists, otherwise use generic temperature. 

I would expect this is not the case. The MQTT climate integration is simply some 'glue' logic to map MQTT traffic to an entity, so whatever comes in will be forwarded.
If a user would command the climate entity to change the setpoint via HA, so via service `climate.set_temperature` with `temperature: <setpoint value>` as data, the new setpoint will probably be output via the `temperature_command_topic` topic only, so if this topic is not set the command will likely be ignored.

**Comment by rwagoner** [comment] 2022-11-07 18:23
@nielsfaber What your saying makes sense, but it doesn't seem to work that way in practice. Let's look at this from a MQTT discovery point of view with a thermostat that supports auto (heat_cool), heat, and cool modes. OmniLinkBridge sends the below for the discovery info at startup. It needs to advertise `temperature_low_` and `temperature_high_` as the mode can be changed at any time between heat, cool, or auto. Home Assistant always shows both setpoints regardless of the mode it is in. The OmniStat 2 thermostats also always show both setpoints. From my knowledge with the current config no issues exists when using the standard Home Assistant climate controls.

```
{
  "status": null,
  "action_topic": "omnilink/thermostat1/current_operation",
  "current_temperature_topic": "omnilink/thermostat1/current_temperature",
  "temperature_low_state_topic": "omnilink/thermostat1/temperature_heat_state",
  "temperature_low_command_topic": "omnilink/thermostat1/temperature_heat_command",
  "temperature_high_state_topic": "omnilink/thermostat1/temperature_cool_state",
  "temperature_high_command_topic": "omnilink/thermostat1/temperature_cool_command",
  "min_temp": "45",
  "max_temp": "95",
  "mode_state_topic": "omnilink/thermostat1/mode_basic_state",
  "mode_command_topic": "omnilink/thermostat1/mode_command",
  "modes": [
    "auto",
    "off",
    "cool",
    "heat"
  ],
  "fan_mode_state_topic": "omnilink/thermostat1/fan_mode_state",
  "fan_mode_command_topic": "omnilink/thermostat1/fan_mode_command",
  "fan_modes": [
    "auto",
    "on",
    "cycle"
  ],
  "preset_mode_state_topic": "omnilink/thermostat1/hold_state",
  "preset_mode_command_topic": "omnilink/thermostat1/hold_command",
  "preset_modes": [
    "off",
    "on",
    "vacation"
  ],
  "unique_id": "omnilinkthermostat1",
  "name": "Main Level",
  "availability": [
    {
      "topic": "omnilink/status"
    },
    {
      "topic": "omnilink/thermostat1/status"
    }
  ],
  "availability_mode": "all",
  "device": {
    "identifiers": "omnilink",
    "name": "omnilink",
    "sw_version": "3.15 - OmniLinkBridge 1.1.14.0",
    "model": "OmniPro II",
    "manufacturer": "Leviton"
  }
}
```

**Closed as completed** 2024-05-04 01:53 UTC
